# This is a sample build configuration for Haskell.
# Do not use tabs to indent your configuration
# You can specify a custom docker image from Dockerhub# for your build environment
image: haskell:8.10.4
pipelines:
   default:
     - step:
         caches:
          - stack-home
          - stack
         script:
           - stack build
           - stack test

definitions:
  caches:
    stack-home: ~/.stack
    stack: .stack-work
