name: atlassian-connect-descriptor
version: '0.4.12.0'
synopsis: Code that helps you create a valid Atlassian Connect Descriptor.
description: ! 'Allows you to generate an Atlassian Connect Descriptor in a typesafe
  manner and easily convert it

  it into JSON using the fantastic Aeson library.'
category: Data
author: Robert Massaioli
maintainer: rmassaioli@atlassian.com
license: Apache-2.0
git: git@bitbucket.org:robertmassaioli/atlassian-connect-descriptor.git
extra-source-files:
- README.markdown
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Data.Connect.Descriptor
  dependencies:
  - base >=4.6 && <5
  - aeson >0.7.0.3
  - text >=0.11 && <=1.3
  - time-units ==1.*
  - cases ==0.1.*
  - unordered-containers ==0.2.*
  when:
  - condition: flag(network-uri)
    then:
      dependencies:
      - network-uri >=2.6
      - network >=2.6
    else:
      dependencies:
      - network-uri <2.6
      - network <2.6
tests:
  test-descriptor:
    main: Main.hs
    source-dirs: tests
    ghc-options: -Wall
    dependencies:
    - base
    - atlassian-connect-descriptor
    - Cabal >=1.20
    - HUnit
    - vector
    - aeson
    - scientific
    - text
    - time-units
    - cases
    - unordered-containers
    - bytestring
    when:
    - condition: flag(network-uri)
      then:
        dependencies:
        - network-uri >=2.6
        - network >=2.6
      else:
        dependencies:
        - network-uri <2.6
        - network <2.6
flags:
  network-uri:
    description: Get Network.URI from the network-uri package
    manual: false
    default: true
